### ISSUE TITLE
Remove faulty float literal initialization from Money type

### ISSUE THREAD

**Issue by tkrajacic** [Flight-School/Guide-to-Numbers-Sample-Code#1]
The book is fantastic as usual but it contains a classic mistake in the Money type: The `ExpressibleByFloatLiteral` fallacy :)

This undos all of the good intentions of having exact values in the type.

```
let m = Money<USD>(floatLiteral: 0.14)
m.amount
```

Here `m.amount` is now **0.14000000000000002048** which is clearly not exact anymore.

The reason I guess is that the literal is always first converted to a `Float`, and only then to a `Decimal`.

If you want any literal initialization, you need to use the String initializer because `Decimal(string: "0.14")` is indeed **0.14** now.

See my related Swift post 
https://forums.swift.org/t/exact-nsdecimalnumber-via-literal/12834

and tracking bugs:
https://bugs.swift.org/browse/SR-3317
https://bugs.swift.org/browse/SR-920

Sure one can argue "but for the purpose of this book…" but that's not what the _Flight School_ books are about. They are precise, and that's what makes them so darn good.

**Comment by mattt** [comment]
Thanks so much for weighing in on this, @tkrajacic, and apologies for not responding sooner.

You're indeed 100% correct on this. I'll be very happy when Swift fixes its literal protocols to not suffer from loss of precision when converting to binary floating point representation.

I'd also love to see proper IEEE 754-2008 `Decimal` types added into the Standard Library at some point, though it's doubtful that anything other than a shim of `Builtin` would make it in (and [Clang doesn't yet have decimal types](https://clang.llvm.org/docs/UsersManual.html), which would be a prerequisite).

But I digress.

My proposed solution for reconciling this in the meantime is two-fold (see 08dfb24 and bbc1138e6):

First, add conformance to `ExpressibleByStringLiteral` and `LosslessStringConvertible` to convert from a lossless decimal string representation:

```swift
extension Money: LosslessStringConvertible {
    public init?(_ description: String) {
        guard let amount = Decimal(string: description) else {
            return nil
        }
        
        self.init(amount)
    }
}
```

This allows for exact initialization from string literals:

```swift
let priceInCNY: Money<CNY> = "19.9"
```

Second, when initializing from a floating-point literal, round the value to the number of places indicated by the `minorUnit` of the associated `Currency` type:

```swift
extension Money: ExpressibleByFloatLiteral {
    public init(floatLiteral value: Double) {
        var approximate = Decimal(floatLiteral: value)
        var rounded = Decimal()
        NSDecimalRound(&rounded, &approximate, Currency.minorUnit, .bankers)
        self.init(rounded)
    }
}
```

The downside to this is that this could lead to unexpected behavior. If someone wants to represent smaller, fractional amounts of money in a currency (for example, [$0.002](https://www.youtube.com/watch?v=MShv_74FNWU) for data usage billing), initializing from a float literal would result in an amount equal to 0. Instead, they would need to initialize using a `Decimal` directly. However, since this use case isn't common, I think an explicit warning in the documentation or, if possible, from the compiler, would be sufficient.

What do you think of this approach, @tkrajacic?

**Comment by tkrajacic** [comment]
This looks like a good path to take, but I am hardly an authority on this topic. I just got bitten by this one too many times ;)

Thank you for the great book!

**Comment by mattt** [comment]
My pleasure! Thanks again for your feedback, @tkrajacic.

I'm excited to announce `Money` as a standalone package. Check it out here: https://github.com/Flight-School/Money
